config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :groups, except: [:index, :show, :delete] do
    resources :messages, only: [:index, :create]
  end
end

# (参考までに残してあります)
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#            user_password PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
#                          POST   /users/password(.:format)            devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#        user_registration PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#                          POST   /users(.:format)                     devise/registrations#create
#                     root GET    /                                    messages#index
#           group_messages GET    /groups/:group_id/messages(.:format) messages#index
#                          POST   /groups/:group_id/messages(.:format) messages#create
#                   groups POST   /groups(.:format)                    groups#create
#                new_group GET    /groups/new(.:format)                groups#new
#               edit_group GET    /groups/:id/edit(.:format)           groups#edit
#                    group PATCH  /groups/:id(.:format)                groups#update
#                          PUT    /groups/:id(.:format)                groups#update
#                          DELETE /groups/:id(.:format)                groups#destroy

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループ作成に成功しました"
    else
      flash.now[:alert] = "グループ作成に失敗しました"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    group = Group.find(params[:id])
    group.update(group_params)
    redirect_to root_path
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/views/groups/_group.html.haml
.content__left__buttom__element
  = link_to group_messages_path(group) do
    %p.content__left__buttom__element__groupname
      = group.name
    %p.content__left__buttom__element__message message

app/views/groups/_group_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class:"chat-group-form__label", for: "chat_group_name"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input", id: "chat_group_name"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: "chat-group-form__input", for: "chat_group_name"
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
        = b.label { b.check_box + b.text }

      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div id='chat-group-users'>
        <div class='chat-group-user clearfix' id='chat-group-user-22'>
        <input name='chat_group[user_ids][]' type='hidden' value='22'>
        <p class='chat-group-user__name'>seo_kyohei</p>
        </div>
        </div>
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "save", class: "chat-group-form__action-btn"

app/views/groups/_group_index.html.haml
.content__left
  .content__left__top
    %p.content__left__top__username
      - if user_signed_in?
        = current_user.name
    .content__left__top__left
      %i.fa.fa-pencil-square-o.fa-2x.set{"aria-hidden" => "true"}
      - if user_signed_in?
        = link_to edit_user_registration_path do
          %i.fa.fa-cog.fa-2x.set{"aria-hidden" => "true"}
      - else
        = link_to new_user_session_path do
          %i.fa.fa-cog.fa-2x.set{"aria-hidden" => "true"}
  .content__left__buttom
    = render @groups

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "group_form"

app/views/groups/index.html.haml
= render partial: "group_index"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: "group_form"